### ISSUE TITLE
UTF-8 should not be supported

### ISSUE THREAD

**Issue by real-or-random** [acatton/flatbencode#2]
I think encoding UTF-8 to bytes silently is not a clean way, 
https://github.com/acatton/flatbencode/blob/master/flatbencode.py#L132
and there is a XXX in the code. ;)

The problem is that it violates the concept that `decode(encode(x))=x` if `x` contains non-ASCII chars. I think the clean Python3 way is to reject strings. Bencoding supports only bytes, so if the user wants to encode a UTF-8 (or whatever) string, he needs to convert it to bytes explicitly.

**Comment by acatton** [comment]
Hm... You are right, indeed. [The specification says](http://www.bittorrent.org/beps/bep_0003.html):

> Dictionaries are encoded as a 'd' followed by a list of alternating keys and their corresponding values followed by an 'e'. For example, `d3:cow3:moo4:spam4:eggse` corresponds to {'cow': 'moo', 'spam': 'eggs'} and `d4:spaml1:a1:bee` corresponds to {'spam': ['a', 'b']}. Keys must be strings and appear in sorted order (sorted as raw strings, not alphanumerics).

That's a good catch. I misinterpreted what 'string' meant in the spec, what they mean is not human readable string, but "bencode strings" which as you describe it are python bytes.

I see two problem, when reading torrent files, as a programmer, you kinda expect doing:

``` python
meta['info']['name']
```

and not:

``` python
meta[b'info'][b'name']
```

which looks dirty. One way to solve this problem is to use a custom subclass of a `dict` that does utf-8 encoded look up when provided a string, but is underneath a map from `bytes` to "bencode value".

I want your opinion on this because to be honest with you, you and I are the only users of `flatbencode`.

Second of all, you are absolutely correct about `decode(encode(x)) == x`. And what I read is "you should use [hypothesis](https://github.com/HypothesisWorks/hypothesis-python) to test this." Which I will.

Also, re-reading the spec calmly, made me realize that `flatbencode` was subject to #3 which I will fix shortly.

Thanks again, and sorry for the late reply, as I said in #1 I didn't receive the email for this, I dunno if github messed up somehow.

**Comment by acatton** [comment]
This issue was fixed in 5bb89a153792f33b0369d3d6f33bca2f6e126949 which was merged in cb82a605fc4a6c8c877d5c6038e9bb0722bce061 however this is still open for discussion.

This is blocking 0.2.0

**Comment by real-or-random** [comment]
Hm, I see that `meta[b'info'][b'name']` is somewhat annoying. 

On the other hand, my feeling is that this is the proper way to do it. If these values are supposed to be byte strings, they should be byte strings. Also, the `b` is not also super ugly. And these keys are anyway magic constants, so it's not bad style to define `INFO = b'info'` if you need it.

Using a class would as you proposed would be complex, and has the problem that then you implicitly need to know whether you should decode a specific value using the UTF-8 or not. The only reason to do a class like that would be that people in practice use UTF-8 strings as dictionary keys often, and I don't think that's the case.

What you could do is to create a class that accepts strings but rejects them if they contain non-ASCII characters, such that writing `meta['info']['name']` would be possible. But that's again complex and hides the fact that keys are byte strings from the programmer. (Explicit is better than implicit.)

**Comment by acatton** [comment]
Your last point is a good point. I'll just release flatbencode v0.2.0 with your fix as is then.

**Comment by real-or-random** [comment]
Wait, but the code still accepts normal UTF-8 strings as dict keys, right? See
https://github.com/acatton/flatbencode/blob/master/flatbencode.py#L135

**Comment by acatton** [comment]
@real-or-random you're correct. That's is something I missed. I'll release a patch for it.

**Comment by acatton** [comment]
Fixed in 0.2.1
